site_name: My Docs
repo_url: https://github.com/John15321/sample_template_package # Your repository URL
repo_name: my-repo-name  # This can be GitHub, GitLab, Bitbucket or anything you want


# https://squidfunk.github.io/mkdocs-material/reference/
theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.hilite
    - content.code.copy
    - navigation.expand
    - toc.collapsible
    - content.details
    - content.footnotes
    - content.katex
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 <a href="https://github.com/John15321"  target="_blank" rel="noopener">Jan Bronicki</a>

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
          show_source: true
          show_category_header: true
          show_root_heading: true
          template: default
          property_order: grouped
          group_properties: true
          enable_inventory: true
          show_dependencies: true
          show_signature_full_path: true

nav:
- 'Home': 'index.md'
- 'Authors': 'authors.md'
- 'Changelog': 'changelog.md'
# rest of the navigation...
# defer to gen-files + literate-nav
- Code Reference: reference/  # 
# rest of the navigation...

